const aliases = {
    '~~': '$DEVD',
    'calias': 'cat ${DEVD}/config/aliases.js',
    'caws': 'cat ~/.aws/credentials',
    'cdbench': 'cd /c/zen_local/bench/',
    'cdcert': 'cd ${DEVD}/cert',
    'cddev': 'cd ${DEVD}',
    'cdd': 'cdev',
    'cdev': 'cddev',
    'cdl': 'cd /c/zen_local/',
    'cdhome': 'cd ~',
    'cdh': 'cd ~',
    'crepos': 'cd /c/zen_local/repos/',
    'cssh': 'cd ~/.ssh/',
    'dl': 'npm run deploy-local',
    'ds': 'serverless deploy',
    'dubu': 'docker run --interactive --tty ubuntu:latest',
    'dz': 'docker start -i zenner',
    'gac': 'git add -A && git commit -m ',
    'gacr': 'gaccr',
    'gaccr': 'git add -A && git commit -m \'conflict resolution\'',
    'gaci': 'git add -A && git commit -m \'initial\'',
    'gc': 'git checkout ',
    'gdp': 'git checkout develop && git pull',
    'gds': 'git diff develop --stat',
    'gitclean': 'git checkout develop | git pull | npm i | git branch --merged | egrep -v \"(^\\*|master|release|develop|goHostLocal)\" | xargs git branch -d',
    'gitdev': 'git checkout develop && git pull && nukenode',
    'gitdiff': 'git diff --name-only',
    'gitecho': 'git branch -al --merged | egrep -v "(^\\*|master|release|develop)" | xargs echo;',
    'gplt': 'npm run lint && npm run test && git push',
    'gpu': 'git push -u',
    'gt': 'gitag',
    'll': 'ls -ahl', // inherit color and other options from 'alias ls'
    'ls': 'ls -F --color=auto --show-control-chars', // enable consistent behavior with bash -il
    'hrep': 'history | grep',
    'napi': 'npm run api-test-local',
    'nb': 'nbuild',
    'nbuild': 'npm run build',
    'nbw': 'npm run build:watch',
    'ndl': 'npm run deploy-local',
    'nix': 'rm -f ./package-lock.json && rm -rf ./node_modules/ix* && npm install',
    'nlint': 'npm run lint',
    'npush': 'ntest && git push',
    'nstart': 'npm run start',
    'ntest': 'clear && npm run test',
    'ntf': 'npm run test-fire',
    'nukeix': 'rm -f ./package-lock.json && rm -rf ./node_modules/ix* && npm install',
    'nukenode': 'rm -f ./package-lock.json && rm -rf ./node_modules/ && npm install',
    'salias': 'source ${DEVD}/receivers/.bash_aliases.js',
    'sbashr': 'source ${DEVD}/receivers/.bashrc',
    'sd': 'serverless deploy',
    'stert': 'npm run start 2> /dev/null || npm run serve',
    'tf': 'npm run test-fire',
    'valias': 'vim ${DEVD}/config/aliases.js'
};

export default aliases;
